apiVersion: v1
kind: Pod
metadata:
  name: phaedra2-commons
  labels:
    ci: phaedra2-commons-build
spec:
  containers:
   - name: builder
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/phaedra2-build-container:latest
     securityContext:
        privileged: true
     resources:
       requests:
         memory: "64Mi"
         cpu: "250m"
       limits:
         memory: "128Mi"
         cpu: "500m"

